services:

  service_a:
    container_name: service_a
    restart: always
    build:
      context: ./serv_A
    ports:
      - 3333:3333
    depends_on:
      - zipkin
      - prometheus
      - otel-collector

  service_b:
    restart: always
    container_name: service_b
    build:
      context: ./serv_B
    env_file:
      - ./serv_B/.env
    ports:
      - 4444:4444
    depends_on:
      - zipkin
      - prometheus
      - otel-collector

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 8888:8888 # Prometeus metrics
      - 8889:8889 # Prometeus exportes metrics
      - 4317:4317 # OTLP gRPC receiver
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
